CRMDemo/Models/Voucher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CRMDemo.Models
{
    public partial class Voucher
    {
        public Voucher()
        {
            Invoices = new HashSet<Invoice>();
        }

        public int Id { get; set; }

        [Display(Name = "Tên voucher")]
        public string VoucherName { get; set; } = null!;

        [Display(Name = "Giá trị")]
        public decimal VoucherValue { get; set; }

        [Display(Name = "Điều kiện")]
        public decimal Condition { get; set; }

        [Display(Name = "Hạn sử dụng")]
        public DateTime Exd { get; set; }

        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}

CRMDemo/Areas/Admin/Controllers/VouchersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRMDemo.Models;

namespace CRMDemo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class VouchersController : Controller
    {
        private readonly CrmDBContext _context;

        public VouchersController(CrmDBContext context)
        {
            _context = context;
        }

        // GET: Admin/Vouchers
        public async Task<IActionResult> Index(string searchString)
        {
            var vouchers = from v in _context.Vouchers
                           select v;
            if (!String.IsNullOrEmpty(searchString))
            {
                vouchers = vouchers.Where(s => s.VoucherName!.Contains(searchString));
            }
            return View(await vouchers.ToListAsync());
        }

        // GET: Admin/Vouchers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vouchers == null)
            {
                return NotFound();
            }

            var voucher = await _context.Vouchers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voucher == null)
            {
                return NotFound();
            }

            return View(voucher);
        }

        // GET: Admin/Vouchers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Vouchers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,VoucherName,VoucherValue,Condition,Exd")] Voucher voucher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(voucher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(voucher);
        }

        // GET: Admin/Vouchers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vouchers == null)
            {
                return NotFound();
            }

            var voucher = await _context.Vouchers.FindAsync(id);
            if (voucher == null)
            {
                return NotFound();
            }
            return View(voucher);
        }

        // POST: Admin/Vouchers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,VoucherName,VoucherValue,Condition,Exd")] Voucher voucher)
        {
            if (id != voucher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(voucher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoucherExists(voucher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(voucher);
        }

        // GET: Admin/Vouchers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vouchers == null)
            {
                return NotFound();
            }

            var voucher = await _context.Vouchers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voucher == null)
            {
                return NotFound();
            }

            return View(voucher);
        }

        // POST: Admin/Vouchers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vouchers == null)
            {
                return Problem("Entity set 'CrmDBContext.Vouchers'  is null.");
            }
            var voucher = await _context.Vouchers.FindAsync(id);
            if (voucher != null)
            {
                _context.Vouchers.Remove(voucher);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VoucherExists(int id)
        {
          return _context.Vouchers.Any(e => e.Id == id);
        }
    }
}

CRMDemo/Areas/Admin/Views/Vouchers/Create.cshtml
@model CRMDemo.Models.Voucher

@{
    ViewData["Title"] = "Create voucher";
    Layout = "~/Areas/Admin/Views/Shared/_VouchersLayout.cshtml";
}

<h1>Thêm voucher mới</h1>

<h4>Voucher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="VoucherName" class="control-label"></label>
                <input asp-for="VoucherName" class="form-control" />
                <span asp-validation-for="VoucherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VoucherValue" class="control-label"></label>
                <input asp-for="VoucherValue" class="form-control" />
                <span asp-validation-for="VoucherValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở lại</a>
</div>

CRMDemo/Areas/Admin/Views/Vouchers/Delete.cshtml
@model CRMDemo.Models.Voucher

@{
    ViewData["Title"] = "Delete voucher";
    Layout = "~/Areas/Admin/Views/Shared/_VouchersLayout.cshtml";
}

<h1>Xóa</h1>

<h3>Bạn thực sự muốn xóa voucher này?</h3>
<div>
    <h4>Voucher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoucherName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoucherName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoucherValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoucherValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Condition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Exd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Exd)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Trở lại</a>
    </form>
</div>

CRMDemo/Areas/Admin/Views/Vouchers/Details.cshtml
@model CRMDemo.Models.Voucher

@{
    ViewData["Title"] = "Details voucher";
    Layout = "~/Areas/Admin/Views/Shared/_VouchersLayout.cshtml";
}

<h1>Chi tiết</h1>

<div>
    <h4>Voucher</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoucherName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoucherName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VoucherValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VoucherValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Condition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Exd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Exd)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Sửa</a> |
    <a asp-action="Index">Trở lại</a>
</div>

CRMDemo/Areas/Admin/Views/Vouchers/Edit.cshtml
@model CRMDemo.Models.Voucher

@{
    ViewData["Title"] = "Edit voucher";
    Layout = "~/Areas/Admin/Views/Shared/_VouchersLayout.cshtml";
}

<h1>Sửa</h1>

<h4>Voucher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="VoucherName" class="control-label"></label>
                <input asp-for="VoucherName" class="form-control" />
                <span asp-validation-for="VoucherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VoucherValue" class="control-label"></label>
                <input asp-for="VoucherValue" class="form-control" />
                <span asp-validation-for="VoucherValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Exd" class="control-label"></label>
                <input asp-for="Exd" class="form-control" />
                <span asp-validation-for="Exd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Trở lại</a>
</div>

CRMDemo/Areas/Admin/Views/Vouchers/Index.cshtml
@model IEnumerable<CRMDemo.Models.Voucher>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_VouchersLayout.cshtml";
}

<h1>Danh sách voucher</h1>

<p>
    <a asp-action="Create">Create New Voucher</a>
</p>
<form asp-controller="Vouchers" asp-action="Index">
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Search" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.VoucherName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VoucherValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Condition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Exd)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.VoucherName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VoucherValue)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Condition)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Exd)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Sửa</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Chi tiết</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>